### ISSUE TITLE
Bug: an error occurs when importing a repository that contains numeric character

### ISSUE THREAD

**Issue by hachi8833** [pointlander/peg#124]
The following peg file causes an error:

> parse error near PegText (line 3 symbol 9 - line 3 symbol 25):
> "github.com/hachi"

```go
package grammar

import "github.com/hachi8833/sample/token"

type Parser Peg {
  token.Program
}

Program <-
    expression EOF
    / expression <.+> {p.Err(begin, buffer)} EOF
    / <.+> {p.Err(begin, buffer)} EOF

expression <-
    additive

additive <-
    multitive (
        '+' multitive {p.PushOpe("+")}
      / '-' multitive {p.PushOpe("-")}
    )*

multitive <-
    value (
        '*' value {p.PushOpe("*")}
      / '/' value {p.PushOpe("/")}
    )*

value <-
    <[0-9]+> {p.PushDigit(text)}
    / '(' expression ')'

EOF                 <- !.
```

Just changing the repository name to like `import "github.com/hachi/sample/token"` works fine.
(My GitHub user name contains some numeric characters😅)

**Comment by pointlander** [comment]
Are you using the latest peg? Try a 'git pull' and 'go install' in your peg directory.

**Comment by pointlander** [comment]
See: https://github.com/pointlander/peg/blob/master/peg.peg#L32

**Comment by hachi8833** [comment]
Worked well! Thank you😂

**Comment by CMogilko** [comment]
Can you tag repo? `go install github.com/pointlander/peg` downloads 2016 version if `GO111MODULE=on`

**Comment by pointlander** [comment]
tagged.
