### ISSUE TITLE
Add example: Arithmetic Calculator

### ISSUE THREAD

**Issue by LazarenkoA** [pointlander/peg#132]
The PEG language seems powerful, but for newcomers, it might be challenging to get started. Could you please add a simple example PEG file for an arithmetic calculator so that beginners can quickly start using your tool?

this example does not work

```
// calculator.peg

Expression  <-  Term (PlusTerm / MinusTerm)*
Term        <-  Factor (MultFactor / DivFactor)*
Factor      <-  "(" Expression ")" / Number
Number      <-  < [0-9]+ >
PlusTerm    <-  "+" Term
MinusTerm   <-  "-" Term
MultFactor  <-  "*" Factor
DivFactor   <-  "/" Factor

~whitespace  <-  [ \t\n\r]*


```

**Comment by pointlander** [comment]
https://github.com/pointlander/peg/blob/master/grammars/calculator/calculator.peg
