### ISSUE TITLE
go generate logs error: exit status 128 due to malformed git call

### ISSUE THREAD

**Issue by mdepot** [pointlander/peg#139]
When running `go generate` or more specifically `go run build.go buildinfo` the buildinfo stage logs:
`buildinfo:2024/09/10 10:55:36 error: exit status 128`

This appears to be because of a malformed call to git in build.go : `func buildinfo()`  Ex:
```
git tag --merged --sort=v:refname
fatal: malformed object name --sort=v:refname
```
At least in the version of git I have, the [--merged \<commit\>] is expecting the next thing passed to be a \<commit\> instead of recognizing --sort as a separate switch.

Consider swapping the order of the switches so --merged is last, or supply a \<commit\> argument to --merged
```
git tag --sort=v:refname --merged
git tag --merged HEAD --sort=v:refname
```

**Comment by meyermarcel** [comment]
I had this issue running `go generate` in my fork. Creating a tag workarounds the issue. Will this help in the short term?

```
git tag v1.0.1
```
