### ISSUE TITLE
Parser completely breaks without warning if you have more than 65536 tokens

### ISSUE THREAD

**Issue by Thordin** [pointlander/peg#37]
I am parsing a medium sized file (60 kb) and the parser breaks if you have more than 16 bits worth of tokens parsed. The AST tree will be completely wrong and it will be missing tokens because it can't have more than 16 bits worth.

I made it work correctly by manually editing the generated file and changed int16 to int32. However it also looks like you preallocated slices like this make([]int32, 1, Math.MaxInt16) which cannot simply be changed to 0 and cannot be changed to MaxInt32 because no one has that much memory. So I changed it to 18 bits, but this obviously will not work for files with more tokens.

I don't feel comfortable submitting a patch for this myself because it looks like this is used in quite a few places and will probably require a significant change to remove these static limits.

**Comment by pointlander** [comment]
Take a look at the Expand function. If you could send me the peg and the
file you are parsing that would be helpful.

**Comment by Thordin** [comment]
Ok it looks like you are expanding the array there. I tried without changing MaxInt16 and it seems to work but the generated file still needs int16 to be changed to int32 elsewhere in order to work.

Here is the full set of test files exhibiting the problem.

http://www.filedropper.com/pegbug

**Comment by pointlander** [comment]
The problem should now be fixed. I should probably remove token16...

**Comment by Thordin** [comment]
I took a quick glance at the commit, and it looks like some int16 were changed to uint16. Doesn't that just double the token limit?

Why not just use int?

**Comment by pointlander** [comment]
The Expand function switches from token16 to token32, but I should get rid
of token16 and just use token32 (or perhaps token64).

**Comment by pointlander** [comment]
fixed
