### ISSUE TITLE
Cannot parse \x00

### ISSUE THREAD

**Issue by mildred** [pointlander/peg#38]
When parsing `[\x00-\x20]` the generator put a NUL character in the generated go file. The go compiler then complains about this NUL character when compiling the file:

    nquads.peg.go: nquads.peg.go:1407:449: illegal character NUL

The generated code looks like:

      /* 9 IRIREF <- <('<' <((!((&('\\') '\\') | (&('`') '`') | (&('^') '^') | (&('|') '|') | (&('}') '}') | (&('{') '{') | (&('"') '"') | (&('>') '>') | (&('<') '<') | (&('\x00' | '\x01' | '\x02' | '\x03' | '\x04' | '\x05' | '\x06' | '\a' | '\b' | '\t' | '\n' | '\v' | '\f' | '\r' | '\x0e' | '\x0f' | '\x10' | '\x11' | '\x12' | '\x13' | '\x14' | '\x15' | '\x16' | '\x17' | '\x18' | '\x19' | '\x1a' | '\x1b' | '\x1c' | '\x1d' | '\x1e' | '\x1f' | ' ') [**<NUL>**- ])) .) / UCHAR)*> Action6 '>')> */

The grammar rule causing this is:

    IRIREF 			<- 	'<' <([^\0x01-\0x20<>"{}|^`\\] / UCHAR)*>{ p.setIri(buffer[begin:end]) } '>'
    UCHAR			<-	'\\u' HEX HEX HEX HEX / '\\U' HEX HEX HEX HEX HEX HEX HEX HEX
    HEX 			<- 	[0-9A-Fa-f]

**Comment by pointlander** [comment]
fixed
