### ISSUE TITLE
Don't matching the longest alternative

### ISSUE THREAD

**Issue by CMogilko** [pointlander/peg#50]
Hi, seems parser don't match the longest alternative, but match first.
Peg:
```
package main

type Test Peg {
}

start <- (keyword / string) ending

ending <- ";"

keyword <- <"KEYWORD"> { fmt.Println("keyword:", buffer[begin:end]) }

string <- <char+> { fmt.Println("string:", buffer[begin:end]) }

char <- .
```
Go:
```
package main

import (
	"log"
)

func main() {
	test := &Test{Buffer: "keyword2;"}
	test.Init()
	if err := test.Parse(); err != nil {
		log.Fatal(err)
	}
	test.Execute()
}
```
It prints error when matching `keyword` rule and seeing unhandled `2`, but right result is `string` rule.

**Comment by pointlander** [comment]
peg doesn't take the longest alternative, just the first to match
this could work for you:

package main

type Test Peg {
}

start <- ( keyword / string ) ending !.

ending <- ";"

keyword <- <"KEYWORD"> &ending { fmt.Println("keyword:", buffer[begin:end])
}

string <- <(!ending char)+> { fmt.Println("string:", buffer[begin:end]) }

char <- .

**Comment by CMogilko** [comment]
it seemed to me that it's like bison with longest match. So, I need to specify in lookahead all possible ending rules? Okay, thx.
