### ISSUE TITLE
Parse and Reset as struct methods instead of struct fields

### ISSUE THREAD

**Issue by maverickwoo** [pointlander/peg#58]
`Parse` and `Reset` are now defined as fields in the generated parser struct, not methods on the struct. One consequence of this choice is that we cannot define an `interface` on the generated struct because `interface` cannot contain fields. This comes up when one wants to abstracts over multiple parsers.

My current workaround is to define wrappers for each generated struct, say:
```go
func (p *Listing) ParseIntf() error {
	return p.Parse()
}
```

and define the interface as (simplified example):
```go
type Listing interface {
	Init()
	ParseIntf() error
	Execute()
}
```

I wish you would consider lifting `Parse` and `Reset` to methods. Thanks!

**Comment by pointlander** [comment]
Does this work for you?: https://github.com/pointlander/peg/commit/de35697c824ea5b18fa773c2dc86694ffdedfbd7

**Comment by maverickwoo** [comment]
Yes. This should work. Thank you!

**Comment by pointlander** [comment]
merged into master
