### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by jaekwon** [pointlander/peg#65]
It doesn't seem like pointlander/peg currently handles memoization.  Is that right?  What's required to make it happen?

**Comment by pointlander** [comment]
pointlander/peg doesn't have memoization. The following data structures
would have to be added:

type Memo struct {
   Matched bool
   Partial []token32
}
var memoization = make(map[uint64]Memo, goodInitialSize)

The key for the memoization map is (rule << 32) | position
Each rule would first check this map and only parse if an entry is not
found.
