### ISSUE TITLE
C grammar fails with trivial but legal C snippet

### ISSUE THREAD

**Issue by bdamm** [pointlander/peg#66]
int main() {
	(a)||1;
}

In general, the two-place operator symbols fail to parse in this configuration (||, &&, ->, >>, <<) as well as the two-place postfix operators ("(a)--", "(a)++").  However I did notice that ">" and "<" also fail.

The key here is the LPAR and RPAR wrapping the expression.  This seems to trigger it.

I'm rather losing my mind over the bug. Any help very much appreciated!

**Comment by bdamm** [comment]
`int a() {// 1 OK
(es);    // 2 OK
1++;     // 3 OK
1+1;     // 4 OK
a+1;     // 5 OK
(a)+1;   // 6 OK
1+(a);   // 7 Not OK
(a)++;   // 8 Not OK
(es)++;  // 9 Not OK
(es)||a; // 10 Not OK
(es)->a; // 11 Not OK
}`

**Comment by bdamm** [comment]
It appears that the grammar only works if the user can define or parse type names semantically and parse them accordingly. With the default grammar file it isn't clear to me how one can do that. I'm exploring ways of having the parser ignore type validity and produce an AST (even if expressions are incorrect) given a correct (syntactically valid, but possibly semantically invalid) C input. So far I have not been able to do it.

**Comment by bdamm** [comment]
I seem to have fixed the issue by making the following grammar change:

```
-CastExpression <- (LPAR TypeName RPAR)* UnaryExpression
+CastExpression <- ((LPAR TypeName RPAR)* UnaryExpression) / UnaryExpression
```

I did try many other permutations, but due to the "greedy" nature of the peg parser, the same pattern that works with the other (binary) operators doesn't work with the (prefix) CastExpression.

Without the immediate branch to UnaryExpression, the parser gets confused and concludes that, e.g. in "1+(a)", the (a) belongs to a CastExpression since there is no knowledge of "a" being a type, and thus the parser cannot reject "a" as a type.

Thus, without significantly more work going in to semantic understanding and a complete typedef table, it is not possible to parse standard C with the given grammar.  With my change, the AST can at least be generated, and for the most part ought to be correct, even without a typedef table.

**Comment by bdamm** [comment]
With my change I have been able to parse a much wider pool of production C code than before.

**Comment by bdamm** [comment]
I'm new to git and not sure how to achieve the pull request. However, the change is https://github.com/bdamm/peg/commit/97181e185fdef7ec63560550d2bc3f3965ffa74f

**Comment by theclapp** [comment]
Creating a pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by bdamm** [comment]
I tried to follow that but when I attempt to create the diff statement the page reloads and there is no longer any button to create the pull request.

**Comment by bdamm** [comment]
The original diff is not the best. Here is a better diff:
```
-CastExpression <- (LPAR TypeName RPAR)* UnaryExpression
+CastExpression <- (LPAR TypeName RPAR CastExpression) / UnaryExpression
```
This allows correct parsing of expressions such as "(char*)(value)". The previous example would allow "(char*)value" but not "(char*)(value)", because it would match twice with the (LPAR UnaryExpression RPAR) and then fail on the "(value)", discarding the entire expression tree. The recursive CastExpression allows the parser to correct capture the leading cast, discard the first attempt at continued match, and fall back to the UnaryExpression matching "(value)".
